name: CampFires
favicon: null
layout_spectrum: 0.11329823173582554
typography_spectrum: 0.9974882013630122
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6370294413063675
  lightness: 0.8157994772773236
  saturation: 0.9752963013015687
  rhythmicContrast: 0.8116827320773154
purpose: []
